#
# Sample MULO configuration file
#

# Server
mulo.api.host=localhost
mulo.api.port=8000

# Jobs
mulo.concurrency=2
mulo.jobs=test
mulo.job.test.run=./test
mulo.job.test.inputs=seconds

# Logging
handlers=java.util.logging.ConsoleHandler
.level=INFO
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tF %1$tT %4$s %5$s%n
