#!/usr/bin/env bash
if [ $# -ne 2 ]; then
    echo "Usage: $(basename "$0") <mulo-endpoint> <job-id>"
    exit 1
fi
MULO=$1
JOB=$2
cnt=0
while true; do
  status_line=$(curl -s "$MULO/status/$JOB")
  read -r status rc <<< "$status_line"
  out=$(curl -sr $cnt- "$MULO/output/$JOB")
  len=${#out}
  cnt=$((cnt + len))
  echo -n "$out"
  if [ "$status" == "queued" ] || [ "$status" == "running" ]; then
    sleep 1
  elif [ "$status" == "failed" ]; then
    echo
    echo "Job $JOB failed: ${status_line:7}"
    exit 100
  else
    echo
    echo "Job $JOB completed with code $rc"
    exit "$rc"
  fi
done
